apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r1wn7yhpa-nodejs 
  janus-idp.io/tekton: r1wn7yhpa-nodejs
  backstage.io/kubernetes-id: r1wn7yhpa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r1wn7yhpa-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml