apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: r1wn7yhpa-nodejs-gitops
  description: This is GitOps manifest for r1wn7yhpa-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=r1wn7yhpa-nodejs
    backstage.io/kubernetes-id: r1wn7yhpa-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: r1wn7yhpa-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:r1wn7yhpa-nodejs
