apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: r1wn7yhpa-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:42dee106e514f0c12da12a6177cbfd35bb1b1036@sha256:069505cbe72d8a9821ce027c7d4c811dc1eaa414dd4c4aadaacf76da82b1463f
          name: container-image
